name: AWS OIDC Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::730335466026:role/new-github-role
          aws-region: us-east-1
          
      - name: list S3 Buckets
        env: 
            aws-region: us-east-1
        run: |
          echo "Printing s3 buckets"
          aws s3 ls